# Imagen oficial publicada desde el repositorio público:
# https://github.com/opensourcepos/opensourcepos
FROM jekkos/opensourcepos:master

LABEL org.opencontainers.image.title="Open Source Point of Sale"
LABEL org.opencontainers.image.source="https://github.com/opensourcepos/opensourcepos"
LABEL org.opencontainers.image.description="POS de prueba conectado a MySQL"

EXPOSE 80
